services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_read_adviser_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLITE_PATH=/data/storage.db
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
